### ISSUE TITLE
add support for pre/post inst/un scripts

### ISSUE THREAD

**Issue by mh-cbon** [mh-cbon/go-msi#2]
like rpm/debian package does, 

it would be a good thing to provide native support 
for those scripts during install/uninstall operations of the package.

TBD

In the manifest, 4 new fields should be provided. 
They target some cmd (powershell?) files. 
When the package is built, somehow they are integrated in the result so that when the package is run, they are executed appropriately.

TODO
- Update manifest to add those 4 fields
- Include those files to the produced msi package
- Update wix flow files to detect, declare and run those scripts as expected

FYI
- http://yentran.org/blog/2013/09/26/wix-batch-file/
- http://stackoverflow.com/questions/170144/how-to-run-a-script-in-wix-with-a-custom-action-simplest-possible-example
- http://stackoverflow.com/questions/2313545/execute-command-line-in-wix-script
- http://wixtoolset.org/documentation/manual/v3/xsd/wix/customaction.html
- https://github.com/damienbod/WiXPowerShellExample
- https://damienbod.com/2013/09/01/wix-installer-with-powershell-scripts/

**Comment by 2opremio** [comment]
I really need this feature. How can I help?

As a workaround, what's the best way to patch the wix templates and hardcode the commands?

**Comment by mh-cbon** [comment]
> As a workaround, what's the best way to patch the wix templates and hardcode the commands?

I guess you refer the hardcoded commands as the new script 
to execute during the installation of the msi.

I d simply add a new field to the manifest 
to declare the path to the bat and its option.

```json
scripts: [
"path/file.bat": { ...options... },
]
```

According to [this example](http://yentran.org/blog/2013/09/26/wix-batch-file/) the [CustomAction](http://wixtoolset.org/documentation/manual/v3/xsd/wix/customaction.html) element is suitable

I d add those new nodes under the [Product Node](https://github.com/mh-cbon/go-msi/blob/master/templates/product.wxs#L13)

That s all i guess.

**Comment by 2opremio** [comment]
Fantastic, thanks!
